[workspace]
resolver = "2"
# when a new core or a module gets created, make sure to define it here when you create it.
members = [ 
    "oll/connection",
    "oll/display",
    "oll/vrserver",
    "oll/tracker",
    "oll/inputs"
]