name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: turtlebrowser/get-conan@v1.0
    
    - name: Install libegl-dev
      run: sudo apt-get install libegl-dev
    
    - name: conan install ..
      run: cd build && conan install .. 
      
    - name: Install dependencies
      run: make
      
